Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroupss
     
  InstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2Instance     

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      
      ImageId: ami-00874d747dde814fa 
    
